---
# 8 volumes on 2 worker nodes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-worker01-pv1
  labels:
    app: minio
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/minio1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ii-k8s-worker01.int.na.intgdc.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-worker02-pv1
  labels:
    app: minio
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/minio1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ii-k8s-worker02.int.na.intgdc.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-worker01-pv2
  labels:
    app: minio
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/minio2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ii-k8s-worker01.int.na.intgdc.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-worker02-pv2
  labels:
    app: minio
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/minio2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ii-k8s-worker02.int.na.intgdc.com
